# Generated by Django 3.0.7 on 2020-07-15 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardemo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cars', models.CharField(max_length=50, null=True, verbose_name='car name')),
                ('img', models.ImageField(blank=True, null=True, upload_to='4wheeler/Images/', verbose_name='Car Image')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_on', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('checksum', models.CharField(blank=True, max_length=100, null=True)),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('p_Phone', models.CharField(max_length=50, null=True, verbose_name='Mobile Number')),
                ('p_emai', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Demo@gmail.com')),
                ('p_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Exact Drop Location')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('p_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PersionInfo',
                'verbose_name_plural': 'PersionInfos',
            },
        ),
        migrations.CreateModel(
            name='OutStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_trip_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Trip Type')),
                ('os_from', models.CharField(blank=True, max_length=100, null=True, verbose_name='FROM city -e.g. Wankidi')),
                ('os_to', models.CharField(blank=True, max_length=100, null=True, verbose_name='TO city -e.g. Hyderabad')),
                ('os_pickup', models.DateField(blank=True, null=True, verbose_name='PICK UP')),
                ('os_return', models.DateField(blank=True, null=True, verbose_name='RETURN')),
                ('os_picktime', models.TimeField(blank=True, null=True, verbose_name='PICK UP AT')),
                ('status', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('os_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OutStation',
                'verbose_name_plural': 'OutStations',
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_trip_for', models.CharField(blank=True, max_length=50, null=True, verbose_name='Trip Type')),
                ('l_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Start typing city -e.g. Wankidi')),
                ('l_pickup', models.DateField(blank=True, null=True, verbose_name='PICK UP')),
                ('l_picktime', models.TimeField(blank=True, null=True, verbose_name='PICK UP AT')),
                ('status', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('l_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locals',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_car', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_page.Cardemo')),
                ('c_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='AirPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ap_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Start typing city -e.g. Hyderabad')),
                ('ap_trip', models.CharField(blank=True, max_length=50, null=True, verbose_name='Trip Type')),
                ('ap_pic_add', models.CharField(blank=True, max_length=100, null=True, verbose_name='Enter your address -e.g. Hyderabad')),
                ('ap_pickup', models.DateField(blank=True, null=True, verbose_name='PICK UP')),
                ('ap_picktime', models.TimeField(blank=True, null=True, verbose_name='PICK UP AT')),
                ('status', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('ap_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AirPort',
                'verbose_name_plural': 'AirPorts',
            },
        ),
    ]
