# Generated by Django 3.0.7 on 2020-07-05 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ap_city', models.CharField(max_length=100, null=True, verbose_name='Start typing city -e.g. Hyderabad')),
                ('ap_trip', models.CharField(choices=[('CFA', 'Car from the Airport'), ('CTA', 'Car to the Airport')], max_length=50, null=True)),
                ('ap_pic_add', models.CharField(max_length=100, null=True, verbose_name='Enter your address -e.g. Hyderabad')),
                ('ap_pickup', models.DateField(null=True, verbose_name='PICK UP')),
                ('ap_picktime', models.TimeField(null=True, verbose_name='PICK UP AT')),
                ('status', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AirPort',
                'verbose_name_plural': 'AirPorts',
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Local', models.CharField(max_length=50)),
                ('l_city', models.CharField(max_length=100, null=True, verbose_name='Start typing city -e.g. Wankidi')),
                ('l_pickup', models.DateField(null=True, verbose_name='PICK UP')),
                ('l_picktime', models.TimeField(null=True, verbose_name='PICK UP AT')),
                ('status', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locals',
            },
        ),
        migrations.CreateModel(
            name='OutStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_trip_type', models.CharField(max_length=50, null=True, verbose_name='Trip Type')),
                ('os_from', models.CharField(blank=True, max_length=100, null=True, verbose_name='FROM city -e.g. Wankidi')),
                ('os_to', models.CharField(max_length=100, null=True, verbose_name='TO city -e.g. Hyderabad')),
                ('os_pickup', models.DateField(null=True, verbose_name='PICK UP')),
                ('os_return', models.DateField(null=True, verbose_name='RETURN')),
                ('os_picktime', models.TimeField(null=True, verbose_name='PICK UP AT')),
                ('status', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OutStation',
                'verbose_name_plural': 'OutStations',
            },
        ),
        migrations.CreateModel(
            name='PersionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('p_Phone', models.CharField(max_length=50, null=True, verbose_name='Mobile Number')),
                ('p_emai', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Demo@gmail.com')),
                ('p_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Exact Drop Location')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('p_ap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_page.AirPort')),
                ('p_local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_page.Local')),
                ('p_os', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_page.OutStation')),
            ],
            options={
                'verbose_name': 'PersionInfo',
                'verbose_name_plural': 'PersionInfos',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_car', models.CharField(max_length=50, null=True, verbose_name='Select Car')),
                ('c_ap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_page.AirPort')),
                ('c_local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_page.Local')),
                ('c_os', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_page.OutStation')),
            ],
        ),
    ]
