# Generated by Django 3.0.7 on 2020-08-25 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Citys',
            new_name='City',
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
    ]
