# Generated by Django 3.0.7 on 2020-07-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='Local',
        ),
        migrations.AlterField(
            model_name='airport',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='outstation',
            name='os_return',
            field=models.DateField(blank=True, null=True, verbose_name='RETURN'),
        ),
        migrations.AlterField(
            model_name='outstation',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
