# Generated by Django 3.0.7 on 2020-07-15 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='c_car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_page.Cardemo'),
        ),
    ]
