# Generated by Django 3.0.7 on 2020-07-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0002_auto_20200705_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='ap_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Start typing city -e.g. Hyderabad'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='ap_pic_add',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Enter your address -e.g. Hyderabad'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='ap_picktime',
            field=models.TimeField(blank=True, null=True, verbose_name='PICK UP AT'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='ap_pickup',
            field=models.DateField(blank=True, null=True, verbose_name='PICK UP'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='ap_trip',
            field=models.CharField(blank=True, choices=[('CFA', 'Car from the Airport'), ('CTA', 'Car to the Airport')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='l_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Start typing city -e.g. Wankidi'),
        ),
        migrations.AlterField(
            model_name='local',
            name='l_picktime',
            field=models.TimeField(blank=True, null=True, verbose_name='PICK UP AT'),
        ),
        migrations.AlterField(
            model_name='local',
            name='l_pickup',
            field=models.DateField(blank=True, null=True, verbose_name='PICK UP'),
        ),
        migrations.AlterField(
            model_name='outstation',
            name='os_picktime',
            field=models.TimeField(blank=True, null=True, verbose_name='PICK UP AT'),
        ),
        migrations.AlterField(
            model_name='outstation',
            name='os_pickup',
            field=models.DateField(blank=True, null=True, verbose_name='PICK UP'),
        ),
        migrations.AlterField(
            model_name='outstation',
            name='os_to',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='TO city -e.g. Hyderabad'),
        ),
        migrations.AlterField(
            model_name='outstation',
            name='os_trip_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Trip Type'),
        ),
    ]
