# Generated by Django 3.0.7 on 2020-08-20 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0002_citys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citys',
            old_name='citys',
            new_name='city_name',
        ),
    ]
