# Generated by Django 3.0.7 on 2020-07-21 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0003_auto_20200715_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='c_airport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_page.AirPort'),
        ),
        migrations.AddField(
            model_name='car',
            name='c_local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_page.Local'),
        ),
        migrations.AddField(
            model_name='car',
            name='c_outstation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_page.OutStation'),
        ),
        migrations.AddField(
            model_name='persioninfo',
            name='p_airport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_page.AirPort'),
        ),
        migrations.AddField(
            model_name='persioninfo',
            name='p_local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_page.Local'),
        ),
        migrations.AddField(
            model_name='persioninfo',
            name='p_outstation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_page.OutStation'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='ap_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Enter Airport Address -e.g. Hyderabad'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='ap_pic_add',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Enter Your Address -e.g. Wankidi'),
        ),
    ]
