# Generated by Django 3.0.7 on 2020-07-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0003_auto_20200706_0047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Car', 'verbose_name_plural': 'Cars'},
        ),
        migrations.AlterField(
            model_name='outstation',
            name='os_trip_type',
            field=models.CharField(blank=True, choices=[('ONE WAY', 'One way'), ('Round Trip', 'Round Trip')], max_length=50, null=True, verbose_name='CHOICES'),
        ),
    ]
