# Generated by Django 3.0.7 on 2020-07-10 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0004_auto_20200706_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardemo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cars', models.CharField(max_length=50, null=True, verbose_name='car name')),
            ],
        ),
        migrations.AddField(
            model_name='outstation',
            name='os_car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_page.Cardemo'),
        ),
    ]
