# Generated by Django 3.0.7 on 2020-07-21 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0004_auto_20200721_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='c_airport',
        ),
        migrations.RemoveField(
            model_name='car',
            name='c_local',
        ),
        migrations.RemoveField(
            model_name='car',
            name='c_outstation',
        ),
        migrations.RemoveField(
            model_name='persioninfo',
            name='p_airport',
        ),
        migrations.RemoveField(
            model_name='persioninfo',
            name='p_local',
        ),
        migrations.RemoveField(
            model_name='persioninfo',
            name='p_outstation',
        ),
        migrations.AddField(
            model_name='outstation',
            name='os_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_page.Car'),
        ),
        migrations.AddField(
            model_name='outstation',
            name='os_persional_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_page.PersionInfo'),
        ),
    ]
