# Generated by Django 3.0.7 on 2020-08-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0004_auto_20200820_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='citys',
            name='airport_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Airport_name'),
        ),
    ]
