# Generated by Django 3.0.7 on 2020-07-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0005_auto_20200710_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardemo',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='4wheeler/Images/', verbose_name='4wheeler Image'),
        ),
    ]
