# Generated by Django 3.0.7 on 2020-07-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0005_auto_20200721_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='outstation',
            name='os_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outstation',
            name='os_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
