# Generated by Django 3.0.7 on 2020-07-21 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0007_auto_20200721_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outstation',
            old_name='created_on',
            new_name='os_created_on',
        ),
        migrations.RenameField(
            model_name='outstation',
            old_name='status',
            new_name='os_status',
        ),
        migrations.RenameField(
            model_name='outstation',
            old_name='updated_on',
            new_name='os_updated_on',
        ),
    ]
