# Generated by Django 3.0.7 on 2020-07-22 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0008_auto_20200721_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='ap_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_page.Car'),
        ),
        migrations.AddField(
            model_name='airport',
            name='ap_persional_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_page.PersionInfo'),
        ),
        migrations.AddField(
            model_name='local',
            name='l_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_page.Car'),
        ),
        migrations.AddField(
            model_name='local',
            name='l_persional_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_page.PersionInfo'),
        ),
        migrations.AddField(
            model_name='local',
            name='l_return',
            field=models.DateField(blank=True, null=True, verbose_name='RETURN'),
        ),
    ]
