# Generated by Django 3.0.7 on 2020-07-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0009_auto_20200722_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardemo',
            name='ac_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Car Ac Price'),
        ),
        migrations.AddField(
            model_name='cardemo',
            name='advance',
            field=models.CharField(blank=True, choices=[('25', '25'), ('50', '50'), ('75', '75'), ('100', '100')], max_length=50, null=True, verbose_name='Adavnce Payment'),
        ),
        migrations.AddField(
            model_name='cardemo',
            name='without_ac_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Car Without Ac Price'),
        ),
    ]
