# Generated by Django 3.0.7 on 2020-07-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0010_auto_20200722_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='c_ac_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='AC Type'),
        ),
    ]
