# Generated by Django 3.0.7 on 2020-07-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0011_car_c_ac_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='l_city',
        ),
        migrations.AddField(
            model_name='airport',
            name='ap_return',
            field=models.DateField(blank=True, null=True, verbose_name='RETURN'),
        ),
        migrations.AddField(
            model_name='local',
            name='l_from',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='From -e.g. Wankidi'),
        ),
        migrations.AddField(
            model_name='local',
            name='l_to',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='To -e.g. Manchirial'),
        ),
    ]
