# Generated by Django 3.0.7 on 2020-07-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0012_auto_20200724_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persioninfo',
            old_name='updated_on',
            new_name='P_updated_on',
        ),
        migrations.RenameField(
            model_name='persioninfo',
            old_name='created_on',
            new_name='p_created_on',
        ),
        migrations.RenameField(
            model_name='persioninfo',
            old_name='p_emai',
            new_name='p_email',
        ),
        migrations.RemoveField(
            model_name='outstation',
            name='os_amount',
        ),
        migrations.RemoveField(
            model_name='outstation',
            name='os_order_id',
        ),
        migrations.AddField(
            model_name='car',
            name='c_advance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='c_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persioninfo',
            name='p_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='ap_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Airport Address -e.g. (RGIA) Rajiv Gandhi International Airport'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='ap_pic_add',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Your Address -e.g. Wankidi'),
        ),
        migrations.AlterField(
            model_name='local',
            name='l_to',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='To -e.g. Mancherial'),
        ),
    ]
