# Generated by Django 3.0.7 on 2020-08-03 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0013_auto_20200725_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='l_trip_for',
        ),
    ]
